name: Python assignment

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check Python Version
        run: python --version

      - name: Dispaly Environment Variables
        run: |
          echo "Application Name: ${{ vars.APP_LATHA }}"
          echo "Environment: ${{ vars.APP_PREE }}"
      - name: Run Python Application
        run: python app.py
